### ISSUE TITLE
Using Ruby gems and Gemfile ?

### ISSUE THREAD

**Issue by oke-aditya** [khushi-411/khushi-411.github.io#3]
Hmm Are you not using any Jekyll plugins and Ruby Gems?

You can use Gems by setting up Ruby locally (rvm / rbenv) and then use bundler.
`bundle` command would install gems.

These gems can be then monitored by dependabot, which would update them automatically :) 
Plus some cool features of jekyll plugins can be used as well. (Worked like charm with minimal mistakes)

E.g. Gemfile https://github.com/oke-aditya/oke-aditya.github.io/blob/master/Gemfile

**Comment by khushi-411** [comment]
That's a great suggestion @oke-aditya!

> These gems can be then monitored by dependabot, which would update them automatically.

I'm pretty much attracted to this feature. Thanks for the idea!
